source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'
use_frameworks! :linkage => :static

target 'ColleagueDemo' do
  pod 'BizFlowKit', :git => 'https://github.com/Immmmmmortal1/BizFlowKit.git', :tag => '0.1.1'
end
